### ISSUE TITLE
Memory Tx Power Not Sticking in v2.6

### ISSUE THREAD

**Issue by gripitoy** [armel/uv-k5-firmware-custom-feat-F4HWN#72]
I'm not sure if it's a feature.

**Previous Behavior (Before v2.6):**

 Let's say you have memory channel 1 set to High Tx power in Chirp, but then lowered it to Low on the radio. If you switched to channel 2, and then back to channel 1, the Tx power for channel 1 would stay at Low, just like you set it on the radio.

**New Behavior (v2.6):**

With the new version (v2.6), adjusting the Tx power on the radio for a channel only affects that channel until you switch to a different channel. Then, the power setting goes back to what was set in Chirp.

**Comment by armel** [comment]
Hi,

Sorry but, if you change the power of a first memory channel from the radio, switch to a second channel and then back to the first, that's right, you'll **get back to the original transmitting power** (as it was, **before** you change it from the radio). It's always been that way. 

The reason is : in memory mode, power is a "_per channel_" parameter. You can change it from the radio. But if you want this change to persist (after changing channel, restarting the pocket, etc.), you need to **save** the memory channel again (via menu 15/63, ChSave).

Regards,

Armel F4HWN.
